language: ruby
before_script:
  - sh -c "cp config/database.sample.yml config/database.yml"
  - sh -c "bundle exec rake db:schema:load"
  - sh -c "bundle exec rake db:seed"
script: "bundle exec rspec"
rvm:
    - 1.9.3
    - 2.2.3
