language: ruby
before_install:
  - "cp config/database.travis.yml config/database.yml"
before_script:
  - sh -c "bundle exec rake tmp:create"
  - sh -c "bundle exec rake db:schema:load"
  - sh -c "bundle exec rake db:seed"
script: "bundle exec rspec"
rvm:
    - 1.9.3
    - 2.2.3
