language: ruby
before_script:
  - cp config/database.sample.yml config/database.yml
  - bundle exec rake db:schema:load
  - bundle exec rake db:seed
script: "bundle exec rspec"
rvm:
    - 1.9.3
    - 2.2.3
